### ISSUE TITLE
内置validator没有使用说明文档

### ISSUE THREAD

**Issue by gogoyqj** [alibaba/noform#17]
src/validate/index.js 

没有使用文档、怎么配置错误信息的国际化 - 没有找到文档

**Comment by gogoyqj** [comment]
最好也能支持 local设置

**Comment by gogoyqj** [comment]
我看了源码，好像没办法对于内置的比如 { required: true } - 这种默认提示进行修改，如果不做点猥琐的事情，就只有手写 message 了

**Comment by quirkyshop** [comment]
@gogoyqj 是的，由于校验现在是直接引入第三方的校验库，后期也会做成可插拔，所以不打算对校验框架做太多定制（猥琐）的事情，手写message也可以接受，如果不是有实时切换多语言的需求的话。先关闭啦~
