### ISSUE TITLE
页面 JS 好像没有上传 DEMO - Simple Example with Ant Design

### ISSUE THREAD

**Issue by William-Sang** [alibaba/noform#4]
https://alibaba.github.io/noform/examples/build  这个 Demo 好像上传的有问题啊。

GET https://alibaba.github.io/static/css/main.1b4f8fcc.css 404 ()

![image](https://user-images.githubusercontent.com/4018929/43877913-dfc243de-9bce-11e8-9905-9afad0fcf0c9.png)

**Comment by liuxuewei** [comment]
@quirkyshop 看下这个问题

**Comment by quirkyshop** [comment]
fix. 上传是需要服务器支持的，antd的demo是自己提供了服务，这里demo没有放出
