### ISSUE TITLE
将ant的TextArea更名成Textarea目的是什么

### ISSUE THREAD

**Issue by sj279811799** [alibaba/noform#7]
使用TextArea时，一直报错，看了下demo，发现名字改成Textarea了

![image](https://user-images.githubusercontent.com/12233760/45273797-dee7a180-b4e6-11e8-9aef-7d76dbe3814b.png)

**Comment by quirkyshop** [comment]
@sj279811799 手抖了👀, 已修正，install下最新(0.0.93)的就好啦
