### ISSUE TITLE
什么时候提供 d.ts 文件呢？

### ISSUE THREAD

**Issue by kostark** [alibaba/noform#8]

**Comment by quirkyshop** [comment]
@kostark 目测在下周某个阳光明媚的日子😝

**Comment by kostark** [comment]
@quirkyshop 深情期待中...

**Comment by quirkyshop** [comment]
@kostark 周末更新下文档和d.ts... 不更是🐶

**Comment by quirkyshop** [comment]
@kostark 1.1.10 ，持续更新中，可能有些参数不太准确，不过基本都列出来了，文档和d.ts优化在下周继续进行 (⊙o⊙)…
